import {
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { migrate } from 'drizzle-orm/bun-sql/migrator';
import {
  closeDatabase,
  getDatabase,
  getDatabaseBootstrapDiagnostics,
  initDatabase
} from '../index';
import { backfillAccountIssuer } from './backfill-account-issuer';
import { seedSmoke } from './seed-smoke';

const MIGRATION_TIMEOUT_S = Number.parseInt(
  process.env.MIGRATION_TIMEOUT ?? '120',
  10
);
const DB_CHECK_TIMEOUT_S = Number.parseInt(
  process.env.DB_CHECK_TIMEOUT ?? '10',
  10
);
const RETRY_INTERVAL_MS = 3000;

/**
 * Migration train boundaries (expand-and-contract).
 *
 * The drizzle migrator applies ALL pending journal entries it can reach in a
 * single transaction, skipping only entries whose `when` is <= the last
 * applied timestamp, and its public API has no way to bound a pass by
 * journal index. To run a data backfill BETWEEN two generated migrations,
 * each pass runs the migrator against a temporary folder whose journal
 * contains exactly the generated entries for that phase — the generated
 * .sql files themselves are copied verbatim and never modified.
 *
 * Phases:
 *   1. journal idx <= ISSUER_TRAIN_EXPAND_IDX  (0007: ADD COLUMN issuer,
 *      nullable)
 *   2. account-issuer backfill (packages/data/src/scripts/
 *      backfill-account-issuer.ts)
 *   3. journal idx >  ISSUER_TRAIN_EXPAND_IDX up to ISSUER_TRAIN_END_IDX
 *      (0008: SET NOT NULL + unique compound index)
 *
 * Once every environment has migrated beyond ISSUER_TRAIN_END_IDX, the
 * whole train becomes a no-op and can collapse back into a single plain
 * migrate() call (delete the train and boundaries).
 *
 * The journal is fail-fast validated against ISSUER_TRAIN_END_IDX so that a
 * newly generated migration (idx > END) can never be silently skipped by
 * the bounded passes — adding one requires extending or collapsing the
 * train on purpose.
 */
const ISSUER_TRAIN_EXPAND_IDX = 7; // 0007_special_fantastic_four
const ISSUER_TRAIN_END_IDX = 8; // 0008_strange_clea
const ISSUER_TRAIN_EXPAND_TAG = '0007_special_fantastic_four';
const ISSUER_TRAIN_END_TAG = '0008_strange_clea';

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

/** Tags are generated by drizzle-kit as `NNNN_lower_snake_codename`. */
const DRIZZLE_TAG_PATTERN = /^[0-9]{4}_[a-z0-9_]+$/;

/**
 * Reads the migrations journal and asserts the train still covers it.
 *
 * Contract: the journal must contain the pinned issuer migrations (idx 7 and
 * 8 with their exact tags) so the in-between backfill runs at the right
 * point. Journal entries beyond the train end are NOT rejected: pass 2 has
 * an unbounded tail, so future plain structural migrations flow through it
 * automatically. Only a migration that needs its own data backfill requires
 * consciously extending the train (see
 * .github/instructions/migrations.instructions.md) — and a constraint
 * migration applied without its backfill still fails loudly at SQL level.
 */
async function readJournalAndAssertTrainCoverage(): Promise<JournalEntry[]> {
  const journal: { entries: JournalEntry[] } = JSON.parse(
    await readFile(join('./migrations', 'meta', '_journal.json'), 'utf8')
  );

  const lastIdx = Math.max(...journal.entries.map((entry) => entry.idx));
  if (lastIdx < ISSUER_TRAIN_END_IDX) {
    throw new Error(
      `Migration train expects journal entries up to idx ${ISSUER_TRAIN_END_IDX} ` +
        `but the journal only reaches idx ${lastIdx}. The issuer migrations appear ` +
        `to have been removed — re-check the train boundaries.`
    );
  }

  // Pin the tags at the train boundaries: if the journal entries at these
  // indexes stop being the issuer migrations, the in-between backfill runs
  // at the wrong point of the train.
  for (const [idx, expectedTag] of [
    [ISSUER_TRAIN_EXPAND_IDX, ISSUER_TRAIN_EXPAND_TAG],
    [ISSUER_TRAIN_END_IDX, ISSUER_TRAIN_END_TAG]
  ] as const) {
    const entry = journal.entries.find((candidate) => candidate.idx === idx);
    if (!entry || entry.tag !== expectedTag) {
      throw new Error(
        `Migration train pin mismatch: journal idx ${idx} is ` +
          `${entry?.tag ?? 'missing'} but the train expects ${expectedTag}. ` +
          `The account issuer backfill must run between these two migrations — ` +
          `re-check the train boundaries.`
      );
    }
  }

  return journal.entries;
}

/**
 * Runs one bounded migrator pass: journal entries with
 * idx > minExclusiveIdx up to (optionally) idx <= maxInclusiveIdx are staged
 * (sql files copied verbatim, journal filtered) into a temp folder and
 * applied via the standard migrator. Already-applied entries are skipped by
 * the migrator itself, so the pass is idempotent.
 */
async function migrateBetween(
  database: Parameters<typeof migrate>[0],
  minExclusiveIdx: number,
  maxInclusiveIdx?: number
): Promise<void> {
  const sourceFolder = './migrations';
  const journal: { entries: JournalEntry[] } = JSON.parse(
    await readFile(join(sourceFolder, 'meta', '_journal.json'), 'utf8')
  );

  const phaseEntries = journal.entries.filter(
    (entry) =>
      entry.idx > minExclusiveIdx &&
      (maxInclusiveIdx === undefined || entry.idx <= maxInclusiveIdx)
  );
  if (phaseEntries.length === 0) return;

  // The journal is trusted checked-in content, but tags are interpolated into
  // file paths below — validate the drizzle-generated format so a malformed
  // or tampered tag cannot traverse directories.
  for (const entry of phaseEntries) {
    if (!DRIZZLE_TAG_PATTERN.test(entry.tag)) {
      throw new Error(
        `Invalid migration tag "${entry.tag}" in journal — expected drizzle-kit format NNNN_codename.`
      );
    }
  }

  const tempFolder = await mkdtemp(join(tmpdir(), 'urlfy-migrate-'));
  try {
    await mkdir(join(tempFolder, 'meta'), { recursive: true });
    await Promise.all(
      phaseEntries.map(async (entry) => {
        await copyFile(
          join(sourceFolder, `${entry.tag}.sql`),
          join(tempFolder, `${entry.tag}.sql`)
        );
      })
    );
    await writeFile(
      join(tempFolder, 'meta', '_journal.json'),
      JSON.stringify({ ...journal, entries: phaseEntries })
    );

    await migrate(database, { migrationsFolder: tempFolder });
  } finally {
    await rm(tempFolder, { recursive: true, force: true });
  }
}

function formatDatabaseTarget(): string {
  const diagnostics = getDatabaseBootstrapDiagnostics();
  const host = diagnostics.host ?? 'unknown-host';
  const port = diagnostics.port ?? 5432;
  const database = diagnostics.database ?? 'unknown-database';
  const sslMode = diagnostics.urlHasSSL ? 'from-url' : 'disable(default)';

  return `${host}:${port}/${database} (ssl=${sslMode}, connect-timeout=${diagnostics.connectionTimeout}s)`;
}

/**
 * Waits for the database to become reachable before running migrations.
 *
 * PostgreSQL is provisioned as a separate Dokploy service and may not be
 * ready immediately when this container starts. We poll with a short
 * interval up to MIGRATION_TIMEOUT seconds rather than failing instantly.
 */
async function waitForDatabase(): Promise<void> {
  const deadline = Date.now() + MIGRATION_TIMEOUT_S * 1000;

  let attempt = 0;
  while (true) {
    attempt++;
    try {
      await initDatabase();
      console.log(`✅ Database reachable (attempt ${attempt})`);
      return;
    } catch (err) {
      const reason = err instanceof Error ? err.message : String(err);
      const remaining = Math.ceil((deadline - Date.now()) / 1000);
      if (remaining <= 0) {
        throw new Error(
          `Database not reachable after ${MIGRATION_TIMEOUT_S}s (${formatDatabaseTarget()}): ${reason}`
        );
      }
      console.log(
        `⏳ Database not ready (attempt ${attempt}, ${remaining}s left): ${reason}`
      );
      // Close any partial connection state before the next attempt
      await closeDatabase();
      await Bun.sleep(RETRY_INTERVAL_MS);
    }
  }
}

async function main() {
  console.log(
    `⏳ Running migrations... (timeout: ${MIGRATION_TIMEOUT_S}s, check-timeout: ${DB_CHECK_TIMEOUT_S}s)`
  );
  console.log(`ℹ️ Database target: ${formatDatabaseTarget()}`);

  try {
    await waitForDatabase();
    const db = getDatabase();

    // Fail fast if the journal no longer contains the pinned issuer
    // migrations (see readJournalAndAssertTrainCoverage) instead of running
    // the backfill at the wrong point of the train.
    await readJournalAndAssertTrainCoverage();

    await migrateBetween(db, -1, ISSUER_TRAIN_EXPAND_IDX);
    console.log('✅ Migration pass 1 completed (expand)');

    const { backfilled } = await backfillAccountIssuer(db);
    console.log(
      `✅ Account issuer backfill completed (${backfilled} row(s) pending at start)`
    );

    await migrateBetween(db, ISSUER_TRAIN_EXPAND_IDX);
    console.log('✅ Migration pass 2 completed successfully (contract)');

    try {
      await seedSmoke(db);
    } catch (seedError) {
      console.error('❌ Post-migration seed failed:', seedError);
      await closeDatabase();
      process.exit(1);
    }

    await closeDatabase();
    process.exit(0);
  } catch (error) {
    console.error('❌ Migration failed:', error);
    await closeDatabase();
    process.exit(1);
  }
}

main();
